name: fake-news
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - transformers
  - numpy
  - pytorch=2.3.0
  - ipykernel
  - scikit-learn
  - pip
  - pip:
    - evaluate
    - accelerate